### ISSUE TITLE
转租信息

### ISSUE THREAD

**Issue by xinlangzi** [xinlangzi/homey#15]
栏目: 类似Real estate News, 需放在主页房源列表的右侧；
-- 允许复制粘贴；
-- members仅可发布文字
-- vip可发布文字+图片

**Comment by haobole** [comment]
@xinlangzi , who can update and delete the sublease notices?

**Comment by haobole** [comment]
@xinlangzi ,

Members only can do plain text. VIP can do rich text (including images). Is this correct?

**Comment by haobole** [comment]
@xinlangzi ,

I did not finish this but I checked in my work so that you could continue if you get time. I am going to a friend's house tonight.

**Comment by xinlangzi** [comment]
@haobole 

Members only can do plain text. VIP can do rich text (including images). Is this correct? **YES**

**Comment by haobole** [comment]
@xinlangzi ,

I have found that if I need to block copying on a page, I have to block it for that whole page. I cannot block it for part of the page and allow it for another part. The reason is that if I want to block it for only a part and the user starts the selecting outside of the forbidden part, he will still be able to copy.

The only thing I can think  of is this: if there are any elements with copy_block on a page, then copying for the whole page will be blocked--even if both sublease and news are on the same page. However, the page has no news but does have sublease info, then copying will be allowed.
